### ISSUE TITLE
Package fails to install on Windows

### ISSUE THREAD

**Issue by AviVahl** [mahirshah/css-property-parser#21]
The .tgz file published to npm contains several files with `*` in their file names:
- `./src/grammars/generated/js/--*.js`
- `./src/grammars/generated/json/--*.json`
- `./src/grammars/generated/nearly/--*.ne`

As * is an illegal file name character on Windows, both yarn and npm fail to fully extract this package, rendering it unusable.

npm output:
```
C:\projects\test> npm i css-property-parser
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\test\node_modules\.staging\css-property-parser-a58395e0\src\grammars\generated\js\--*.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\test\node_modules\.staging\css-property-parser-a58395e0\src\grammars\generated\json\--*.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\projects\test\node_modules\.staging\css-property-parser-a58395e0\src\grammars\generated\nearley\--*.ne'
npm WARN saveError ENOENT: no such file or directory, open 'C:\projects\test\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\projects\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ css-property-parser@1.0.5
added 15 packages in 2.607s
```

Would it be possible to re-publish the last version with cross-platform compatible file-names? :)

**Comment by chriseppstein** [comment]
Hi, thanks for the great diagnosis. `v1.0.6` is released and those files have been renamed. Can you please verify if this release works for you?

**Comment by AviVahl** [comment]
Verified as installing correctly with both npm and yarn.
Thanks for the prompt response and bugfix release! 👍
